# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\上课\大二下\数据库原理与设计\大作业\hospital\doctor_reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(859, 869)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/login/huashan_login2.jpeg"))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_21.addWidget(self.label_15)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.lineEdit_id_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_id_3.setObjectName("lineEdit_id_3")
        self.horizontalLayout_17.addWidget(self.lineEdit_id_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_18.addWidget(self.label_17)
        self.lineEdit_id_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_id_4.setObjectName("lineEdit_id_4")
        self.horizontalLayout_18.addWidget(self.lineEdit_id_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_18, 2, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.lineEdit_pwd_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_pwd_5.setObjectName("lineEdit_pwd_5")
        self.horizontalLayout_19.addWidget(self.lineEdit_pwd_5)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_19, 3, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem8)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_20.addWidget(self.label_19)
        self.lineEdit_pwd_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_pwd_6.setObjectName("lineEdit_pwd_6")
        self.horizontalLayout_20.addWidget(self.lineEdit_pwd_6)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem9)
        self.gridLayout.addLayout(self.horizontalLayout_20, 4, 0, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem10)
        self.pushButton_regit_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_regit_3.setObjectName("pushButton_regit_3")
        self.horizontalLayout_22.addWidget(self.pushButton_regit_3)
        self.pushButton_cancel_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel_3.setObjectName("pushButton_cancel_3")
        self.horizontalLayout_22.addWidget(self.pushButton_cancel_3)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem11)
        self.gridLayout.addLayout(self.horizontalLayout_22, 5, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.pushButton_cancel_3.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_16.setText(_translate("Dialog", "医生id号："))
        self.label_17.setText(_translate("Dialog", "姓    名："))
        self.label_18.setText(_translate("Dialog", "密    码："))
        self.label_19.setText(_translate("Dialog", "重复密码："))
        self.pushButton_regit_3.setText(_translate("Dialog", "注册"))
        self.pushButton_cancel_3.setText(_translate("Dialog", "取消"))
import resouce_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
