# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\python_workplace\hospital\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionguahao = QtWidgets.QAction(MainWindow)
        self.actionguahao.setObjectName("actionguahao")
        self.action_reg = QtWidgets.QAction(MainWindow)
        self.action_reg.setObjectName("action_reg")
        self.action_med = QtWidgets.QAction(MainWindow)
        self.action_med.setObjectName("action_med")
        self.actionguahao_2 = QtWidgets.QAction(MainWindow)
        self.actionguahao_2.setObjectName("actionguahao_2")
        self.actionquyao = QtWidgets.QAction(MainWindow)
        self.actionquyao.setObjectName("actionquyao")
        self.actionadzhuyuanpat = QtWidgets.QAction(MainWindow)
        self.actionadzhuyuanpat.setObjectName("actionadzhuyuanpat")
        self.actionjiaohao = QtWidgets.QAction(MainWindow)
        self.actionjiaohao.setObjectName("actionjiaohao")
        self.actionkaiyao = QtWidgets.QAction(MainWindow)
        self.actionkaiyao.setObjectName("actionkaiyao")
        self.actionzhuyuandoc = QtWidgets.QAction(MainWindow)
        self.actionzhuyuandoc.setObjectName("actionzhuyuandoc")
        self.menu.addAction(self.actionguahao_2)
        self.menu.addAction(self.actionquyao)
        self.menu.addAction(self.actionadzhuyuanpat)
        self.menu_2.addAction(self.actionjiaohao)
        self.menu_2.addAction(self.actionkaiyao)
        self.menu_2.addAction(self.actionzhuyuandoc)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "病患登录"))
        self.menu_2.setTitle(_translate("MainWindow", "医生登录"))
        self.menu_3.setTitle(_translate("MainWindow", "设置"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionguahao.setText(_translate("MainWindow", "guahao "))
        self.action_reg.setText(_translate("MainWindow", "挂号"))
        self.action_med.setText(_translate("MainWindow", "取药"))
        self.actionguahao_2.setText(_translate("MainWindow", "挂号"))
        self.actionquyao.setText(_translate("MainWindow", "取药"))
        self.actionadzhuyuanpat.setText(_translate("MainWindow", "住院单"))
        self.actionjiaohao.setText(_translate("MainWindow", "叫号"))
        self.actionkaiyao.setText(_translate("MainWindow", "开药"))
        self.actionzhuyuandoc.setText(_translate("MainWindow", "住院医嘱"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
